/**
 * Référentiels embarqués pour l'étape « Enrichir » des recettes de préparation (fonctionnement hors ligne) :
 * pays ISO 3166 avec devise, devises ISO 4217 avec symbole, départements français avec région.
 * Mêmes valeurs que l'application classique.
 */

export type Referentiel = { label: string; key: string; cols: string[]; rows: string[][] };

export const REFERENTIELS: Record<string, Referentiel> = {
    pays: {
        label: 'Pays (ISO 3166)',
        key: 'CODE',
        cols: ['CODE', 'PAYS', 'DEVISE'],
        rows: [
            ['FR', 'France', 'EUR'],
            ['DE', 'Allemagne', 'EUR'],
            ['IT', 'Italie', 'EUR'],
            ['ES', 'Espagne', 'EUR'],
            ['PT', 'Portugal', 'EUR'],
            ['BE', 'Belgique', 'EUR'],
            ['NL', 'Pays-Bas', 'EUR'],
            ['LU', 'Luxembourg', 'EUR'],
            ['CH', 'Suisse', 'CHF'],
            ['GB', 'Royaume-Uni', 'GBP'],
            ['IE', 'Irlande', 'EUR'],
            ['AT', 'Autriche', 'EUR'],
            ['PL', 'Pologne', 'PLN'],
            ['CZ', 'Tchéquie', 'CZK'],
            ['SE', 'Suède', 'SEK'],
            ['NO', 'Norvège', 'NOK'],
            ['DK', 'Danemark', 'DKK'],
            ['FI', 'Finlande', 'EUR'],
            ['GR', 'Grèce', 'EUR'],
            ['RO', 'Roumanie', 'RON'],
            ['HU', 'Hongrie', 'HUF'],
            ['US', 'États-Unis', 'USD'],
            ['CA', 'Canada', 'CAD'],
            ['MX', 'Mexique', 'MXN'],
            ['BR', 'Brésil', 'BRL'],
            ['AR', 'Argentine', 'ARS'],
            ['CN', 'Chine', 'CNY'],
            ['JP', 'Japon', 'JPY'],
            ['KR', 'Corée du Sud', 'KRW'],
            ['IN', 'Inde', 'INR'],
            ['AU', 'Australie', 'AUD'],
            ['NZ', 'Nouvelle-Zélande', 'NZD'],
            ['MA', 'Maroc', 'MAD'],
            ['DZ', 'Algérie', 'DZD'],
            ['TN', 'Tunisie', 'TND'],
            ['SN', 'Sénégal', 'XOF'],
            ['CI', "Côte d'Ivoire", 'XOF'],
            ['CM', 'Cameroun', 'XAF'],
            ['TR', 'Turquie', 'TRY'],
            ['SA', 'Arabie saoudite', 'SAR'],
            ['AE', 'Émirats arabes unis', 'AED'],
            ['ZA', 'Afrique du Sud', 'ZAR'],
            ['RU', 'Russie', 'RUB'],
            ['UA', 'Ukraine', 'UAH'],
            ['SG', 'Singapour', 'SGD'],
            ['HK', 'Hong Kong', 'HKD'],
            ['TH', 'Thaïlande', 'THB'],
            ['VN', 'Viêt Nam', 'VND'],
            ['ID', 'Indonésie', 'IDR'],
            ['MY', 'Malaisie', 'MYR']
        ]
    },
    devises: {
        label: 'Devises (ISO 4217)',
        key: 'CODE',
        cols: ['CODE', 'DEVISE', 'SYMBOLE'],
        rows: [
            ['EUR', 'Euro', '€'],
            ['USD', 'Dollar américain', '$'],
            ['GBP', 'Livre sterling', '£'],
            ['CHF', 'Franc suisse', 'CHF'],
            ['JPY', 'Yen', '¥'],
            ['CNY', 'Yuan', '¥'],
            ['CAD', 'Dollar canadien', '$'],
            ['AUD', 'Dollar australien', '$'],
            ['SEK', 'Couronne suédoise', 'kr'],
            ['NOK', 'Couronne norvégienne', 'kr'],
            ['DKK', 'Couronne danoise', 'kr'],
            ['PLN', 'Zloty', 'zł'],
            ['CZK', 'Couronne tchèque', 'Kč'],
            ['HUF', 'Forint', 'Ft'],
            ['RON', 'Leu', 'lei'],
            ['TRY', 'Livre turque', '₺'],
            ['MAD', 'Dirham marocain', 'DH'],
            ['XOF', 'Franc CFA (UEMOA)', 'CFA'],
            ['XAF', 'Franc CFA (CEMAC)', 'CFA'],
            ['INR', 'Roupie indienne', '₹'],
            ['BRL', 'Réal', 'R$'],
            ['MXN', 'Peso mexicain', '$'],
            ['SGD', 'Dollar de Singapour', '$'],
            ['HKD', 'Dollar de Hong Kong', '$'],
            ['ZAR', 'Rand', 'R'],
            ['AED', 'Dirham (EAU)', 'د.إ'],
            ['SAR', 'Riyal saoudien', '﷼'],
            ['KRW', 'Won', '₩'],
            ['THB', 'Baht', '฿'],
            ['RUB', 'Rouble', '₽']
        ]
    },
    deptfr: {
        label: 'Départements français',
        key: 'CODE',
        cols: ['CODE', 'DEPARTEMENT', 'REGION'],
        rows: [
            ['01', 'Ain', 'Auvergne-Rhône-Alpes'],
            ['02', 'Aisne', 'Hauts-de-France'],
            ['03', 'Allier', 'Auvergne-Rhône-Alpes'],
            ['04', 'Alpes-de-Haute-Provence', 'PACA'],
            ['05', 'Hautes-Alpes', 'PACA'],
            ['06', 'Alpes-Maritimes', 'PACA'],
            ['07', 'Ardèche', 'Auvergne-Rhône-Alpes'],
            ['08', 'Ardennes', 'Grand Est'],
            ['09', 'Ariège', 'Occitanie'],
            ['10', 'Aube', 'Grand Est'],
            ['11', 'Aude', 'Occitanie'],
            ['12', 'Aveyron', 'Occitanie'],
            ['13', 'Bouches-du-Rhône', 'PACA'],
            ['14', 'Calvados', 'Normandie'],
            ['15', 'Cantal', 'Auvergne-Rhône-Alpes'],
            ['16', 'Charente', 'Nouvelle-Aquitaine'],
            ['17', 'Charente-Maritime', 'Nouvelle-Aquitaine'],
            ['18', 'Cher', 'Centre-Val de Loire'],
            ['19', 'Corrèze', 'Nouvelle-Aquitaine'],
            ['2A', 'Corse-du-Sud', 'Corse'],
            ['2B', 'Haute-Corse', 'Corse'],
            ['21', "Côte-d'Or", 'Bourgogne-Franche-Comté'],
            ['22', "Côtes-d'Armor", 'Bretagne'],
            ['23', 'Creuse', 'Nouvelle-Aquitaine'],
            ['24', 'Dordogne', 'Nouvelle-Aquitaine'],
            ['25', 'Doubs', 'Bourgogne-Franche-Comté'],
            ['26', 'Drôme', 'Auvergne-Rhône-Alpes'],
            ['27', 'Eure', 'Normandie'],
            ['28', 'Eure-et-Loir', 'Centre-Val de Loire'],
            ['29', 'Finistère', 'Bretagne'],
            ['30', 'Gard', 'Occitanie'],
            ['31', 'Haute-Garonne', 'Occitanie'],
            ['32', 'Gers', 'Occitanie'],
            ['33', 'Gironde', 'Nouvelle-Aquitaine'],
            ['34', 'Hérault', 'Occitanie'],
            ['35', 'Ille-et-Vilaine', 'Bretagne'],
            ['36', 'Indre', 'Centre-Val de Loire'],
            ['37', 'Indre-et-Loire', 'Centre-Val de Loire'],
            ['38', 'Isère', 'Auvergne-Rhône-Alpes'],
            ['39', 'Jura', 'Bourgogne-Franche-Comté'],
            ['40', 'Landes', 'Nouvelle-Aquitaine'],
            ['41', 'Loir-et-Cher', 'Centre-Val de Loire'],
            ['42', 'Loire', 'Auvergne-Rhône-Alpes'],
            ['43', 'Haute-Loire', 'Auvergne-Rhône-Alpes'],
            ['44', 'Loire-Atlantique', 'Pays de la Loire'],
            ['45', 'Loiret', 'Centre-Val de Loire'],
            ['46', 'Lot', 'Occitanie'],
            ['47', 'Lot-et-Garonne', 'Nouvelle-Aquitaine'],
            ['48', 'Lozère', 'Occitanie'],
            ['49', 'Maine-et-Loire', 'Pays de la Loire'],
            ['50', 'Manche', 'Normandie'],
            ['51', 'Marne', 'Grand Est'],
            ['52', 'Haute-Marne', 'Grand Est'],
            ['53', 'Mayenne', 'Pays de la Loire'],
            ['54', 'Meurthe-et-Moselle', 'Grand Est'],
            ['55', 'Meuse', 'Grand Est'],
            ['56', 'Morbihan', 'Bretagne'],
            ['57', 'Moselle', 'Grand Est'],
            ['58', 'Nièvre', 'Bourgogne-Franche-Comté'],
            ['59', 'Nord', 'Hauts-de-France'],
            ['60', 'Oise', 'Hauts-de-France'],
            ['61', 'Orne', 'Normandie'],
            ['62', 'Pas-de-Calais', 'Hauts-de-France'],
            ['63', 'Puy-de-Dôme', 'Auvergne-Rhône-Alpes'],
            ['64', 'Pyrénées-Atlantiques', 'Nouvelle-Aquitaine'],
            ['65', 'Hautes-Pyrénées', 'Occitanie'],
            ['66', 'Pyrénées-Orientales', 'Occitanie'],
            ['67', 'Bas-Rhin', 'Grand Est'],
            ['68', 'Haut-Rhin', 'Grand Est'],
            ['69', 'Rhône', 'Auvergne-Rhône-Alpes'],
            ['70', 'Haute-Saône', 'Bourgogne-Franche-Comté'],
            ['71', 'Saône-et-Loire', 'Bourgogne-Franche-Comté'],
            ['72', 'Sarthe', 'Pays de la Loire'],
            ['73', 'Savoie', 'Auvergne-Rhône-Alpes'],
            ['74', 'Haute-Savoie', 'Auvergne-Rhône-Alpes'],
            ['75', 'Paris', 'Île-de-France'],
            ['76', 'Seine-Maritime', 'Normandie'],
            ['77', 'Seine-et-Marne', 'Île-de-France'],
            ['78', 'Yvelines', 'Île-de-France'],
            ['79', 'Deux-Sèvres', 'Nouvelle-Aquitaine'],
            ['80', 'Somme', 'Hauts-de-France'],
            ['81', 'Tarn', 'Occitanie'],
            ['82', 'Tarn-et-Garonne', 'Occitanie'],
            ['83', 'Var', 'PACA'],
            ['84', 'Vaucluse', 'PACA'],
            ['85', 'Vendée', 'Pays de la Loire'],
            ['86', 'Vienne', 'Nouvelle-Aquitaine'],
            ['87', 'Haute-Vienne', 'Nouvelle-Aquitaine'],
            ['88', 'Vosges', 'Grand Est'],
            ['89', 'Yonne', 'Bourgogne-Franche-Comté'],
            ['90', 'Territoire de Belfort', 'Bourgogne-Franche-Comté'],
            ['91', 'Essonne', 'Île-de-France'],
            ['92', 'Hauts-de-Seine', 'Île-de-France'],
            ['93', 'Seine-Saint-Denis', 'Île-de-France'],
            ['94', 'Val-de-Marne', 'Île-de-France'],
            ['95', "Val-d'Oise", 'Île-de-France']
        ]
    }
};
