import fs from 'fs';
// Chemins : racine studio-data et dossier des suites (surchargeables par l'environnement, voir tests/run.mjs)
const ROOT = process.env.SD_ROOT || new URL('../../', import.meta.url).pathname;
const D = new URL('./', import.meta.url).pathname;
const { chromium } = (await import(process.env.PLAYWRIGHT_INDEX || '/opt/node22/lib/node_modules/playwright/index.js')).default;
const CHROMIUM = process.env.CHROMIUM || '/opt/pw-browsers/chromium-1194/chrome-linux/chrome';
const html = fs.readFileSync(ROOT + 'StudioDataV11.html','utf8').replace(/<script src="https:[^"]*"[^>]*><\/script>/g,'').replace(/<link[^>]*rel="stylesheet"[^>]*>/g,'');
const b = await chromium.launch({ executablePath: CHROMIUM });
const p = await b.newPage({ viewport: { width: 1500, height: 950 } });
const perr=[]; p.on('pageerror',e=>{ if(!/lucide/.test(String(e))) perr.push(String(e)); }); p.on('console', m=>{ if(m.type()==='error' && !/lucide|favicon|net::|CSP|Content Security/.test(m.text())) perr.push('console: '+m.text()); });
await p.setContent(html,{waitUntil:'domcontentloaded'}); await p.addStyleTag({ path: D+'tw/tw_built.css' });
await p.waitForTimeout(1500);
const out = await p.evaluate(async ()=>{
  const R=[]; const log=(n,v)=>R.push(n+': '+v);
  window.lucide={createIcons:()=>{}};
  log('version', APP_VERSION+' / '+APP_CHANGELOG[0].v+' / title='+document.title);
  log('tour visible', !!document.getElementById('v11Tour'));
  v11TourEnd(true);
  log('topbar', !!document.getElementById('v11Save') && !!document.getElementById('v11Hist'));
  switchPhase('gov'); log('tab entrée', govState.tab);
  log('accueil vide', document.getElementById('govContent').textContent.includes('Charger un exemple'));
  v11LoadSample();
  log('après exemple', govState.tab+' objets='+state.governance.businessObjects.length+' toast='+(document.querySelector('.v11-toast')||{}).textContent);
  log('menu familles', Array.from(document.querySelectorAll('.v11-fam')).map(x=>x.textContent).join('|'));
  const bo=state.governance.businessObjects[0]; v11GoBo(bo.id);
  log('fiche lecture', !!document.querySelector('#v11-bo-'+bo.id)+' rows='+document.querySelectorAll('#v11-bo-'+bo.id+' tbody tr').length+' crumb='+document.getElementById('govCrumb').textContent);
  v11ToggleEdit('bo',bo.id); log('edit mode', !!document.querySelector('.v11-editbar')+' collapsed='+document.body.classList.contains('v7-collapsed')+' cols='+!!document.querySelector('.v11-cols'));
  v11ToggleEdit('bo',bo.id);
  openGovTab('glossary'); log('termes lecture', document.querySelectorAll('.v11-fiche').length);
  openGovTab('assets'); log('applis lecture', document.querySelectorAll('.v11-fiche').length);
  govState.dictMode='table'; openGovTab('dictionary'); log('dictionnaire', (document.querySelector('.v11-fiche .kind')||{}).textContent+' / '+document.getElementById('govContent').textContent.slice(0,80));
  openGovTab('home'); log('accueil rempli', document.getElementById('govContent').textContent.includes('Fiches à compléter')+' '+document.querySelectorAll('.v11-card').length);
  v11PaletteOpen(); document.getElementById('v11PalIn').value='client'; document.getElementById('v11PalIn').dispatchEvent(new Event('input')); log('palette', document.querySelectorAll('#v11PalRes .it').length+' first='+(document.querySelector('#v11PalRes .it')||{}).textContent); v11PaletteGo(0); log('palette go', govState.tab+' '+(document.querySelector('.v11-fiche h2')||{}).textContent);
  v11Fs('#v11-bo-'+bo.id,'X'); log('fs', !!document.getElementById('v11Fs')+' '+!!document.querySelector('#v11Fs .v11-fiche')); v11FsClose(); log('fs closed', !document.getElementById('v11Fs')+' '+!!document.querySelector('#govContent .v11-fiche'));
  v11Back(); log('back', govState.tab); v11Fwd(); log('fwd', govState.tab);
  const before=JSON.stringify(state.governance.businessObjects[0].definition); updateBusinessObject(bo.id,'definition','Nouvelle déf'); log('undo stack', v11State.undo.length); v11Undo(); log('undo', state.governance.businessObjects[0].definition);
  v11HelpOpen(); log('help', !!document.getElementById('v11Help')); v11HelpClose();
  v11WizardOpen(); document.getElementById('wz-name').value='Site'; v11WizardNext(); v11WizardNext(); const nb=v11WizardFinish(); log('wizard', nb && nb.name+' tab='+govState.tab+' n='+state.governance.businessObjects.length);
  v11BulkOpen(bo.id); log('bulk', !!document.getElementById('bk-act')); v11ModalClose();
  return R;
});
out.forEach(x=>console.log(x)); console.log('errors:', perr.length); perr.slice(0,8).forEach(e=>console.log('  ',e));
await p.screenshot({ path: D+'v11_smoke.png' });
await b.close();
